repos:
  # Ruff - replaces black, isort, pylint, and bandit
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      # Linting (includes security checks)
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --extend-exclude, predict ]
        stages: [ pre-commit ]
      # Formatting (replaces black)
      - id: ruff-format
        args: [ --exclude, predict ]
        stages: [ pre-commit ]

  # Type checking
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "bash -lc 'cd .. && domains/.venv/bin/python -m mypy domains --config-file=domains/mypy.ini --exclude domains/predict'"
        language: system
        types: [ python ]
        require_serial: true
        stages: [ pre-commit ]
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -lc 'echo "Skipping domains tests (predict excluded)"'
        language: system
        pass_filenames: false
        always_run: true
        stages: [ pre-push ]
        require_serial: true

  # Additional useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        stages: [ pre-commit ]
      - id: check-added-large-files
        args: ['--maxkb=100000']  # 100MB limit
        stages: [ pre-commit ]
      - id: check-merge-conflict
        stages: [ pre-commit ]
      - id: debug-statements
        stages: [ pre-commit ]
